# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  bloom-benchmarks:
    dependencies:
    - base
    - bloom
    - bloomfilter
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: bloom is a new Haskeleton package.
executables:
  bloom:
    dependencies:
    - base
    - bloom
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: asoltysik/haskell-bloom-streaming
library:
  dependencies:
  - base < 5
  - mtl
  - vector
  - Dish
  - cereal
  - random
  source-dirs: library
  other-modules: 
  - Internal.BitVector
  - Internal.Hashing
license: MIT
maintainer: Andrzej Sołtysik
name: bloom
synopsis: Implementation of Stable Bloom Filter for unbounded streams. 
tests:
  boom-test-suite:
    dependencies:
    - base
    - bloom
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
